<?xml version="1.0" encoding="utf-8"?><Database Name="LMSDatabase" Class="LMSConnectionDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\LMSDatabase.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="LMSDatabaseConnectionString" Provider="System.Data.SqlClient" />
</Database>